use_frameworks!

platform :ios, '8.0'

target 'SIMMapKit_Category_Example' do
  pod 'SIMMapKit_Category', :path => '../'

  target 'SIMMapKit_Category_Tests' do
    inherit! :search_paths

    
  end
end
